name: Format Java Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Check for Java files
        id: check_java_files
        run: |
          CHANGED_FILES=$(git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }} | grep '\.java$' || true)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Java files changed."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Java files changed."
            echo "skip=false" >> $GITHUB_ENV
            echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV
          fi

      - name: Ensure tools directory exists
        run: mkdir -p tools

      - name: Check if Google Java Format JAR exists
        id: check_format_jar
        run: |
          if [ -f tools/google-java-format-1.22.0-all-deps.jar ]; then
            echo "format_jar_exists=true" >> $GITHUB_ENV
          else
            echo "format_jar_exists=false" >> $GITHUB_ENV
          fi

      - name: Download Google Java Format JAR
        if: env.skip == 'false' && env.format_jar_exists == 'false'
        run: |
          curl -L -o tools/google-java-format-1.22.0-all-deps.jar https://repo1.maven.org/maven2/com/google/googlejavaformat/google-java-format/1.22.0/google-java-format-1.22.0-all-deps.jar

      - name: Run Google Java Format
        if: env.skip == 'false'
        run: |
          for FILE in ${{ env.changed_files }}; do
            echo "Formatting $FILE"
            java -jar tools/google-java-format-1.22.0-all-deps.jar --aosp $FILE
          done

      - name: Commit and push changes
        if: env.skip == 'false'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Automatically format Java code'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Skip message
        if: env.skip == 'true'
        run: echo "No Java files to format. Action skipped."
