name: Format Java Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Find changed Java files
        id: get_changed_files
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.java$' || true)
          elif [ "${{ github.event_name }}" == "push" ]; then
            CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '\.java$' || true)
          else
            CHANGED_FILES=""
          fi
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Format Java files
        run: |
          if [ -n "$CHANGED_FILES" ]; then
            for FILE in $CHANGED_FILES; do
              java -jar google-java-format-1.22.0-all-deps.jar --aosp --replace "$FILE"
            done
          else
            echo "No Java files changed"
          fi

      - name: Commit and push changes
        if: success() && env.CHANGED_FILES != ''
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Automatically format changed lines in Java code'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
