name: Format Java Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Check for Java files
        id: check_java_files
        run: |
          if [ -z "$(find . -name '*.java')" ]; then
            echo "No Java files found."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "Java files found."
            echo "skip=false" >> $GITHUB_ENV
          fi

      - name: Format Java code
        if: env.skip == 'false'
        run: java -jar tools/google-java-format-1.22.0-all-deps.jar -r $(find . -name '*.java')

      - name: Commit and push changes
        if: env.skip == 'false'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m 'Automatically format Java code'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Skip message
        if: env.skip == 'true'
        run: echo "No Java files to format. Action skipped."
