name: Auto-merge PRs

on:
  pull_request_review:
    types:
      - submitted

permissions:
  contents: write
  pull-requests: write

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.review.state == 'approved' && contains(fromJson('["dependabot[bot]", "octocat", "iyadKhamis", "eyadashrafkh", "adham404"]'), github.actor) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Info for Auto-Merge
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"
          echo "Review State: ${{ github.event.review.state }}"
          echo "Token: ${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
