name: Enable automerge on specific users PRs and dependabot PRs

run-name: ${{ github.actor }} is testing auto-merging 🚀

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore:
      - .github/workflows/your-workflow-file.yml  # Replace with your actual workflow file name

jobs:
  automerge:
    name: Enable automerge on specific users PRs and dependabot PRs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PR Creator is in the List of Users
        id: check_user
        run: |
          USERS_JSON='["user1", "user2", "user3", "dependabot[bot]", "iyadKhamis"]'
          echo "USERS_JSON=${USERS_JSON}"
          if echo "$USERS_JSON" | jq -e ".[] == \"${{ github.actor }}\"" >/dev/null; then
            echo "USER_IN_LIST=true" >> $GITHUB_ENV
            echo "True"
          else
            echo "USER_IN_LIST=false" >> $GITHUB_ENV
            echo "False"
          fi

      - name: Set auto-merge conditions
        id: auto_merge_conditions
        run: |
          echo "Checking conditions..."          
          if [ "${USER_IN_LIST}" = "true" ] && [ "${{ github.event.pull_request.draft }}" = "false" ]; then
            echo "AUTO_MERGE=true" >> $GITHUB_ENV
            echo "True"
          else
            echo "AUTO_MERGE=false" >> $GITHUB_ENV
            echo "false"
          fi

      - name: Check Token Availability
        run: |
          if [ -z "${{ secrets.PERSONAL_ACCESS_TOKEN }}" ]; then
            echo "PERSONAL_ACCESS_TOKEN is not set."
            exit 1
          else
            echo "PERSONAL_ACCESS_TOKEN is set."
          fi

      - name: Test Token with API Call
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" https://api.github.com/user)
          echo "$response"
          if echo "$response" | grep -q '"login":'; then
            echo "Token is working."
          else
            echo "Token is not working."
            exit 1
          fi

      - name: Auto Merge Bot
        if: ${{ env.AUTO_MERGE == 'true' }}
        uses: daneden/enable-automerge-action@v1
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use your personal access token from repository secrets
          allowed-author: "dependabot[bot], iyadKhamis"
          merge-method: MERGE
          
      - name: No Merge Due to Conditions Not Met
        if: ${{ env.AUTO_MERGE == 'false' }}
        run: |
          echo "No merge due to conditions not met. User is either not in the list, PR is a draft, or PR is not in a clean state."
          echo "AUTO_MERGE=${{ env.AUTO_MERGE }}"

      - name: Merge Due to Conditions Met
        if: ${{ env.AUTO_MERGE == 'true' }}
        run: |
          echo "Merge due to conditions met. User is in the list and PR is ready for merge."
          echo "AUTO_MERGE=${{ env.AUTO_MERGE }}"
