name: Auto-merge PRs

on: pull_request_target

# permissions:
#   contents: write
#   pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson('["dependabot[bot]", "octocat", "iyadKhamis", "eyadashrafkh"]'), github.actor) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug Info
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "PR URL: ${{ github.event.pull_request.html_url }}"
          echo "Token: ${{ secrets.GITHUB_TOKEN }}"
        
      # - name: Approve a PR
      #   run: gh pr review --approve "$PR_URL"
      #   env:
      #     PR_URL: ${{github.event.pull_request.html_url}}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Enable auto-merge for PRs
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: Merge Pull Request
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: gh pr merge ${{ github.event.pull_request.number }} --merge --admin
