name: Auto-Merge PR on Approval
on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR can be merged
        id: check_pr
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const approvedReviewers = ['adham404'];  // Replace with actual usernames
            const prNumber = context.payload.pull_request.number;
            const { data: reviews } = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
            const approved = reviews.some(review => approvedReviewers.includes(review.user.login) && review.state === 'approved');
            return approved ? 'true' : 'false';

      - name: Merge PR
        if: steps.check_pr.outputs.result == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });
